// lib/features/summaries/summaries_screen.dart

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/navigation.dart';
import '../../core/theme/theme.dart';
import '../../core/widgets/widgets.dart';
import '../../data/models/summary_section.dart';
import '../flashcards/flashcards_screen.dart';
import '../quiz/quiz_screen.dart';
import 'summaries_view_model.dart';

class SummariesScreen extends ConsumerWidget {
  const SummariesScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final sf = context.sf;
    final scheme = context.scheme;
    final open = ref.watch(openSummarySectionProvider);
    final bookmarked = ref.watch(summaryBookmarkedProvider);
    final material = ref.watch(summaryMaterialProvider).value;
    final sections = ref.watch(summarySectionsProvider);

    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(22, 12, 22, 14),
              child: Row(
                children: [
                  SfIconButton(
                    icon: Icons.arrow_back_rounded,
                    onPressed: () => Navigator.of(context).pop(),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        SfEyebrow('Summary', tracking: 1),
                        Text(
                          material?.title ?? 'Loading…',
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            fontFamily: AppTextStyles.fontUi,
                            fontSize: 16,
                            fontWeight: FontWeight.w700,
                            letterSpacing: -0.3,
                            color: sf.ink,
                          ),
                        ),
                      ],
                    ),
                  ),
                  SfIconButton(
                    icon: bookmarked
                        ? Icons.bookmark_rounded
                        : Icons.bookmark_border_rounded,
                    iconSize: 16,
                    onPressed:
                        ref.read(summaryBookmarkedProvider.notifier).toggle,
                  ),
                ],
              ),
            ),

            // Provenance banner
            Padding(
              padding: const EdgeInsets.fromLTRB(22, 0, 22, 14),
              child: Container(
                padding: const EdgeInsets.all(14),
                decoration: BoxDecoration(
                  color: sf.indigoSoft,
                  borderRadius: AppRadius.brMd,
                  border: Border.all(
                      color: scheme.primary.withValues(alpha: 0.12)),
                ),
                child: Row(
                  children: [
                    const FlowOrb(size: 20),
                    const SizedBox(width: 10),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Generated by Flow · '
                            '${material?.pageCount ?? 0} pages → '
                            '${sections.value?.length ?? 0} sections',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w700,
                              letterSpacing: -0.1,
                              color: scheme.primary,
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            material?.subjectName ?? '',
                            style: TextStyle(fontSize: 11, color: sf.ink3),
                          ),
                        ],
                      ),
                    ),
                    GestureDetector(
                      onTap: () => ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text('Regenerating needs the AI service'),
                        ),
                      ),
                      child: Icon(Icons.refresh_rounded,
                          size: 18, color: scheme.primary),
                    ),
                  ],
                ),
              ),
            ),

            // Sections
            Expanded(
              child: sections.when(
                loading: () => const SfLoadingList(rows: 4, height: 64),
                error: (error, _) => SfErrorView(
                  error: error,
                  onRetry: () => ref.invalidate(summarySectionsProvider),
                ),
                data: (items) => items.isEmpty
                    ? const SfEmptyView(
                        icon: Icons.auto_awesome_outlined,
                        title: 'No summary yet',
                        body: 'Flow builds these from an uploaded document.',
                      )
                    : ListView.separated(
                        padding: const EdgeInsets.fromLTRB(22, 0, 22, 8),
                        itemCount: items.length,
                        separatorBuilder: (_, _) => const SizedBox(height: 10),
                        itemBuilder: (context, i) => _SummarySectionTile(
                          section: items[i],
                          index: i,
                          open: open == i,
                          // Tapping the open section collapses it.
                          onToggle: () => ref
                              .read(openSummarySectionProvider.notifier)
                              .update(open == i ? -1 : i),
                        ),
                      ),
              ),
            ),

            // Actions
            Padding(
              padding: const EdgeInsets.fromLTRB(22, 12, 22, 16),
              child: Row(
                children: [
                  Expanded(
                    child: SfButton(
                      'Flashcards',
                      variant: SfButtonVariant.secondary,
                      icon: Icons.style_outlined,
                      expand: true,
                      onPressed: () => Navigator.of(context).push(
                        sfModalRoute(
                            builder: (_) => const FlashcardsScreen()),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: SfButton(
                      'Quiz me',
                      icon: Icons.help_outline_rounded,
                      expand: true,
                      onPressed: () => Navigator.of(context).push(
                        sfModalRoute(builder: (_) => const QuizScreen()),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  SfButton.iconOnly(
                    icon: Icons.ios_share_rounded,
                    onPressed: () {},
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _SummarySectionTile extends StatelessWidget {
  const _SummarySectionTile({
    required this.section,
    required this.index,
    required this.open,
    required this.onToggle,
  });

  final SummarySection section;
  final int index;
  final bool open;
  final VoidCallback onToggle;

  @override
  Widget build(BuildContext context) {
    final sf = context.sf;
    final scheme = context.scheme;
    final hasBody = section.bullets.isNotEmpty;

    return SfCard(
      padding: EdgeInsets.zero,
      clip: true,
      child: Column(
        children: [
          InkWell(
            onTap: onToggle,
            child: Padding(
              padding:
                  const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
              child: Row(
                children: [
                  Container(
                    width: 24,
                    height: 24,
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      color: section.read
                          ? sf.emeraldSoft
                          : scheme.surfaceContainerHigh,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: section.read
                        ? Icon(Icons.check_rounded,
                            size: 14, color: sf.emeraldInk)
                        : SfMono('${index + 1}',
                            size: 11, weight: FontWeight.w700),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      section.title,
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w700,
                        letterSpacing: -0.1,
                        color: sf.ink,
                      ),
                    ),
                  ),
                  AnimatedRotation(
                    turns: open ? 0.5 : 0,
                    duration: const Duration(milliseconds: 200),
                    child: Icon(Icons.keyboard_arrow_down_rounded,
                        size: 18, color: sf.ink3),
                  ),
                ],
              ),
            ),
          ),
          AnimatedSize(
            duration: const Duration(milliseconds: 200),
            curve: Curves.easeOut,
            alignment: Alignment.topCenter,
            child: !open || !hasBody
                ? const SizedBox(width: double.infinity)
                : Padding(
                    padding: const EdgeInsets.fromLTRB(52, 0, 16, 16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        for (final b in section.bullets)
                          Padding(
                            padding: const EdgeInsets.only(bottom: 8),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  margin: const EdgeInsets.only(top: 8),
                                  width: 4,
                                  height: 4,
                                  decoration: BoxDecoration(
                                    shape: BoxShape.circle,
                                    color: scheme.primary,
                                  ),
                                ),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: MarkedText(
                                    b,
                                    accentColor: scheme.primary,
                                    style: TextStyle(
                                      fontSize: 13,
                                      height: 1.5,
                                      color: sf.ink2,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                      ],
                    ),
                  ),
          ),
        ],
      ),
    );
  }
}
